### ISSUE TITLE
user-can-choose-currency

### ISSUE THREAD

**Issue by saraysc** [saraysc/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can track the weather of the location they'll visit

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can track the weather of the location they'll visit

## 🖼️ Wireframes

<img width="184" alt="image" src="https://user-images.githubusercontent.com/113648549/203611201-19f1cc71-916d-4b96-95b9-9d41541d7236.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ]Query the DOM for the 'form' element.
- [ ]Create a new XMLHttpRequest() object.
open() the xhr object to send a 'GET' request to 'https://www.freeforexapi.com/api/live'
- [ ]Set the responseType
- [ ]Listen for the 'load' event on the xhr object in order to:
- [ ]check the currency and find the corresponding rate
- [ ]send() the request to begin loading the data from the server.
- [ ]Multiply the corresponding rate to the price input

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
