### ISSUE TITLE
user-add-location

### ISSUE THREAD

**Issue by saraysc** [saraysc/ajax-project#2]
## ⚙️ Feature

Users can create a list of the places they’ll be visiting

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The list of itinerary will add the new location the user will visit

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="219" alt="image" src="https://user-images.githubusercontent.com/113648549/201795668-74153906-3df9-4b60-8393-b5cf06903b21.png">
<img width="398" alt="image" src="https://user-images.githubusercontent.com/113648549/201795720-fe019227-e531-4ac3-998e-0a947674c788.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Choose the location the user will be visiting
- [ ] Listen for `'Add Itinerary'` events on the journal entry form and:
  - [ ] Put the form's input values into a new object.
  - [ ] Add the `location` to the object.
  - [ ] Prepend the new object to the entries in the data model.
  - [ ] Reset the form inputs.
  - [ ] Show the page with all the itineraries saved
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
