### ISSUE TITLE
usar-add-time-date

### ISSUE THREAD

**Issue by saraysc** [saraysc/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add time and date value to the object

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can add time and date value to the list so they can check everytime is necessary

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113648549/201796209-e49753d0-a67e-4019-9dbb-c66c67adffe1.png)
![image](https://user-images.githubusercontent.com/113648549/201796226-ecd0caa3-4572-4d1a-a143-c08fe7e32cae.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Choose the date and time the user will be visiting the location
 - [ ] Listen for 'Add Itinerary' events on the journal entry form and:
 - [ ] Put the form's input values into a new object.
 - [ ] Add the time and date value to the object.
 - [ ] Prepend the new object to the entries in the data model.
- [ ]  Reset the form inputs.
 - [ ] Show the page with all the itineraries saved
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
