### ISSUE TITLE
user-add-expense

### ISSUE THREAD

**Issue by saraysc** [saraysc/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can add how much they'll spending in the location

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can check how much they'll be spending to visit the location

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113648549/201796747-a5fca9bd-7476-45bc-a333-8097032a062b.png)
![image](https://user-images.githubusercontent.com/113648549/201796759-6dd6dfe5-6fac-4aa3-b074-2aecfb30ee14.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Choose the expense of the user when visiting the location
 - [ ] Listen for 'Add Itinerary' events on the journal entry form and:
- [ ]  Put the form's input values into a new object.
 - [ ] Add the expense to the object.
 - [ ] Prepend the new object to the entries in the data model.
 - [ ] Reset the form inputs.
 - [ ] Show the page with all the itineraries saved
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
