### ISSUE TITLE
user-review-location

### ISSUE THREAD

**Issue by saraysc** [saraysc/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can 'like' a location

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

'Like' functionality to show the visit is important/exciting

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="217" alt="image" src="https://user-images.githubusercontent.com/113648549/201797298-8735ff4d-a58d-4c86-adec-bf2ee6f9999a.png">
![image](https://user-images.githubusercontent.com/113648549/201797704-eab3ed11-87b8-406e-9eef-66e572dd9d97.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ]  Listen for the heart icon events on the journal entry form and:
- [ ]  When clicked, the heart will be filled in the color black.
- [ ] Add the heart value to the object.
- [ ] Prepend the new object to the entries in the data model.

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
