### ISSUE TITLE
user-remove-itinerary

### ISSUE THREAD

**Issue by saraysc** [saraysc/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

If the users change their mind and they don't want to visit the location anymore, they can delete the itinerary from the list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can remove itinerary from the list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="221" alt="image" src="https://user-images.githubusercontent.com/113648549/201798144-c334ce5e-5f55-4c17-81b6-c871dced20fe.png">
<img width="396" alt="image" src="https://user-images.githubusercontent.com/113648549/201798183-0ed0e1b9-4cad-4f48-9420-b14c2c837a6a.png">
<img width="403" alt="image" src="https://user-images.githubusercontent.com/113648549/201798207-344d4895-786c-4822-a5a0-1932ce908783.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a click target for deleting an itinerary from the form that only appears if the user is editing an entry.
 - [x] Show a confirmation modal when the user clicks the Delete Itinerary click target.
  - [ ]Hide the modal if the user clicks Cancel.
  - [ ]Remove the entry from the data model and the entry's DOM tree from the page if the user clicks Delete.
  - [ ]Show the Entries list if the user clicks Delete.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
